/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddbookRouteImport } from './routes/addbook'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DetailsIdRouteImport } from './routes/details/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddbookRoute = AddbookRouteImport.update({
  id: '/addbook',
  path: '/addbook',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsIdRoute = DetailsIdRouteImport.update({
  id: '/details/$id',
  path: '/details/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addbook': typeof AddbookRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/details/$id': typeof DetailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addbook': typeof AddbookRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/details/$id': typeof DetailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addbook': typeof AddbookRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/details/$id': typeof DetailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/addbook' | '/login' | '/register' | '/details/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/addbook' | '/login' | '/register' | '/details/$id'
  id: '__root__' | '/' | '/addbook' | '/login' | '/register' | '/details/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddbookRoute: typeof AddbookRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DetailsIdRoute: typeof DetailsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addbook': {
      id: '/addbook'
      path: '/addbook'
      fullPath: '/addbook'
      preLoaderRoute: typeof AddbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details/$id': {
      id: '/details/$id'
      path: '/details/$id'
      fullPath: '/details/$id'
      preLoaderRoute: typeof DetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddbookRoute: AddbookRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DetailsIdRoute: DetailsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
